version: "1.0"
info:
  model: int-scaffold
packages:
- name: DefectTest1Project
  gitServerName: ICAccountTest0311
  gitUrl: https://github.com/amlanbhowmick85/DefectTest1Project
  gitUsername: amlanbhowmick85
  gitBranch: main
